# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'  

variables:
  solution: 'Source\Zafiro.sln'
  projects: 'Source\Zafiro.Core\Zafiro.Core.csproj;Source\Zafiro.Avalonia\Zafiro.Avalonia.csproj;Source\Zafiro.Avalonia.Design\Zafiro.Avalonia.Design.csproj'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'
  major: 2
  minor: 2
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  NugetVersion: $(major).$(minor).$(patch)

steps:
- checkout: self
  submodules: recursive

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'Source\Zafiro.Wpf\Zafiro.Wpf.csproj'

- task: VSBuild@1
  displayName: Build Zafiro.Wpf
  inputs:
    solution: 'Source\Zafiro.Wpf\Zafiro.Wpf.csproj'    
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: Create Zafiro.Wpf Package
  inputs:
    command: 'pack'
    packagesToPack: 'Source\Zafiro.Wpf\Zafiro.Wpf.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'NugetVersion'

- task: DotNetCoreCLI@2
  displayName: Create .NET Standard Packages with .NET Core (dotnet)
  inputs:
    command: 'pack'
    packagesToPack: '$(projects)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'NugetVersion'

- task: NuGetCommand@2
  displayName: Publish NuGet packages
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'